name: geospatial
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - python=3.11.11  # (Specify your Python version if needed)
  - paramiko
  - python-dotenv
  - libgdal-hdf4
  - pip
  - pip:
    - temporalio
    - azure-storage-blob
    - geopandas
    - rasterio
    - earthaccess
    - netCDF4
    - shapely
    - xarray
    - h5py
    - pyhdf