name: geospatial
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - python=3.11.11  # (Specify your Python version if needed)
  - paramiko
  - python-dotenv
  - pip
  - pip:
    - temporalio
